os: osx
language: objective-c
before_install:
  - brew tap chrihop/gcc_cross_compilers
  - brew tap homebrew/dupes
env:
  - ARCH=x86_64
  - ARCH=arm
  - ARCH=i386
script:
  - sh test.sh
branches:
  only:
    - master
notifications:
  recipients:
    - chrihop@gmail.com
  email:
    on_success: always
    on_failure: always
